export const SCIENCE_REQUEST_BROADCAST  = "SCIENCE_REQUEST_BROADCAST";
export const SCIENCE_REQUEST_SUCCESS    = "SCIENCE_REQUEST_SUCCESS";
export const SCIENCE_REQUEST_FAILURE    = "SCIENCE_REQUEST_FAILURE";