export const POLITICS_REQUEST_BROADCAST  = "POLITICS_REQUEST_BROADCAST";
export const POLITICS_REQUEST_SUCCESS    = "POLITICS_REQUEST_SUCCESS";
export const POLITICS_REQUEST_FAILURE    = "POLITICS_REQUEST_FAILURE";